services:
  php-fpm:
    build:
      args:
        container_project_path: /var/www/html/
      context: .
      dockerfile: ./Dockerfile
    image: php-fpm
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
      - redis

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    image: bagisto-nginx
    expose:
      - "80"
    depends_on:
      - php-fpm

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bagisto
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin:latest
    expose:
      - "80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 2G
      MEMORY_LIMIT: 2G
      MAX_EXECUTION_TIME: 600

  redis:
    image: redis:6.2-alpine
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  mailpit:
    image: "axllent/mailpit:latest"

volumes:
  mysql-data:
  redis-data:
  elasticsearch-data:
